version: '3'
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  ping_pong_bot:
    build:
      context: .
      dockerfile: dockerfile.txt
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    links:
      - "db:db"
    ports:
      - "8080:8080"
    depends_on:
      - db
